cli:
  - changed-files:
      - any-glob-to-any-file: "cli/**"

app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

site:
  - changed-files:
      - any-glob-to-any-file: "site/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "site/src/pages/docs/**"

types:
  - changed-files:
      - any-glob-to-any-file: "types/**"

infra:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
      - any-glob-to-any-file: "infra/**"
