cli:
  - changed-files:
      - any-glob-to-any-file: "cli/**"

app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

site:
  - changed-files:
      - any-glob-to-any-file: "site/**"

infra:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
      - any-glob-to-any-file: "infra/**"
